"""Add license_type to driver_licenses

Revision ID: 9bc86343dc56
Revises: 
Create Date: 2025-09-21 02:42:36.578070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc86343dc56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('driver_licenses', sa.Column('license_type', sa.String(), nullable=True))
    
    # Update existing records to have a default value
    op.execute("UPDATE driver_licenses SET license_type = 'front' WHERE license_type IS NULL")
    
    # Now make the column non-nullable
    op.alter_column('driver_licenses', 'license_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_licenses', 'license_type')
    # ### end Alembic commands ###
